const PackagingInstruction=()=>{
    return(
        <div className="w-ful flex flex-col items-center justify-center">
            <div className="relative w-full flex items-center justify-center">
                <div className='w-full h-[150px] md:h-[300px] bg-black'>
                </div>
                <div className='absolute'>
                    <h1 className='text-white font-inter font-medium text-xl md:text-5xl'>Packaging Instruction</h1>
                </div>
            </div>
            <div className="w-11/12 bg-pale-mint flex items-center justify-center flex-col p-2 md:p-6 my-2 rounded-md shadow-md shadow-deep-green">
                <div className="w-full pb-5 md:pb-8">
                        <h1 className="font-inter text-[15px] md:text-lg font-semibold text-[#000000cc] my-3">PACKAGING INSTRUCTIONS</h1>
                        <ul className="list-disc pl-6">
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">The items shall be packed using carton boxes and the same shall be sealed using proper packaging tapes.</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Documents shall be packed using the envelopes with proper sealing.</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Do not use damaged or old boxes for packaging.</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Fragile items shall be packed inside thick carton box by filling the voids with foam/crumpled paper</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Ensure that the right labels are printed and pasted on the package.</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Remove any old labels or barcodes.</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Avoid using low-quality adhesive tapes, Kraft paper tape, cellophane, masking tapes, and springs or ropes</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Only one box/envelope is allowed per AWB number</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Packing and Labeling: It is the sender's obligation to ensure adequate packing for the purpose of carriage with normal care in handling</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">In case the Shipment is inappropriately packed and/or it contains any of the prohibited items to the knowledge of MyFastX, the Shipment may be flagged as Rejected by the pickup person assigned with such tasks</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">The maximum allowable size of the package for the MyFastX courier is 100,000 cubic cms</li>
                        </ul>
                </div>
                <div className="w-full pb-5 md:pb-8">
                        <h1 className="font-inter text-[15px] md:text-lg font-semibold text-[#000000cc] my-3">GENERAL INSTRUCTIONS</h1>
                        <ul className="list-disc pl-6">
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">If any discrepancy in weight is found post-acceptance of a consignment and if the actual weight or volumetric weight is greater than the declared weight, then the differential applicable charges shall be collected from the Parties</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">In order to carry out successful pickup and delivery of goods, customer details may be shared with the service provider by MyFastX</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">The Parties shall pay all such payments as may be required to be made to statutory bodies or Municipal or State/Central Government agencies with respect to any consignment during transit or at the time of delivery</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">The sender shall provide the complete address of the sender and recipient along with valid contact telephone numbers and the correct Postal Index Number (PIN code). Any service failure arising out of any defect in such details shall be at the sole responsibility & risk of the sender</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">The consignment note is issued strictly based on the declaration given by the parties at the time of booking. The Parties shall remain solely liable for any consequences arising out of any false or wrongful declaration</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">In the event of any consignment being held up by any statutory authorities such as, but not limited to, Goods and Services Tax, Excise, Customs, Check-Post officials, e-way bill, etc. MyFastX shall not be responsible for any consequential losses or for refund of freight charges. Further, the Parties agree to make good to MyFastX any losses incurred by MyFastX, in the form of taxes/ duties, fines and penalties levied by statutory authorities arising out of insufficiency of documents or wrongful declaration and any claims, if any, from any other entity affected because of delays arising out of issues related to such consignments</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Inspection of consignment: MyFastX has the right at its option or at the request of competent authorities to open consignments at any time to inspect the contents of the consignment as part of the acceptance process and/or at various MyFastX consignment handling points and/or at airline security gates and/or on request by any statutory, regulatory or security agencies</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">If the Parties do not take delivery of the consignment or it remains undelivered due to any reason such as wrong or incomplete address or refusal by recipient to pay any applicable duties / taxes / charges or containing prohibited items or if the packaging of a consignment is damaged to the extent that repacking is not possible resulting in non-delivery or the consignment is found as likely to cause damage to other goods or cause injury to individuals, then the Parties shall still be liable to pay freight charges and all other dues and charges to MyFastX. In case of the consignment remain undelivered beyond 48 hours from the date of tendering the consignment for delivery, then demurrage / warehouse charges at the rate of 0.1% of the consignment invoice value per day will be charged or at such other rates as may be fixed by MyFastX from time to time. If the consignment is not received or claimed within a month from the date of tendering the consignment for delivery for the first time, then the MyFastX shall have the right to proceed with the sale of the goods to realize all its dues</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Directors, owners, partners and shareholders of MyFastX shall not be personally liable for any claims or liabilities arising out of service failures resulting out of situations, circumstances, omissions, errors, failures or misleading statements/guidance from any employees of MyFastX or of its channel partners or of its authorized agents</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">In the event of non-delivery of a shipment, the consignor can opt for the shipment to be returned. Consignors will be liable to MyFastX reserves for the reverse movement charges. For the same, the return address is set as the same address registered as the sender's/consignor's address at the time of booking. Sender to agree that when a shipment comes back as RTO (return to origin) due to failed delivery, or any other reason whatsoever, it is the sender responsibility to confirm the order to RTO to MyFastX in with the Reverse Airway bill number. Sender agrees to make payment as applicable</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">At the time of booking parcels, the consignor will be required to provide a declaration stating the value of the consignment and the detailed description of materials in the consignment and the same shall be binding on the consignor. If the consignee is not declaring the value of shipment, it will be considered as zero</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">MyFastX will use the consignor / consignee information as shared, to update and inform the consignor / consignee through SMS, Whatsapp and/ or email regarding the delivery status of the product and obtain feedback from the consignor / consignee regarding the said service only so as to improve the customer experience with MyFastX. Further, MyFastX or its affiliates may share promotional information or offers regarding the services provided by MyFastX only at the option of the user and at all times the user shall be in its right to opt out from receiving such information</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Shipments cannot be delivered to PO boxes or postal codes. Shipments are delivered to the consignee's address as provided by the consignor but not necessarily to the named consignee personally. Shipments to addresses with a central receiving area will be delivered to that area only</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">If the consignee refuses delivery or the shipment is deemed to be unacceptable, or it has been undervalued for customs purposes, or if the consignee is not reasonably identified or located, MyFastX will make reasonable efforts to return the shipment to the consignor's address at the consignor's cost only. If MyFastX is unable to return the said shipments due to reasons attributable to the consignor alone or due to any reason beyond the control of MyFastX, the shipment may be released, disposed of by MyFastX, without incurring any liability/penalty whatsoever in this regard. Further, MyFastX will bear no liability for the same towards the consignor or any third party</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">It is not possible to entertain any request for updating the delivery address once the shipment leaves the city of origin. However, consignors can make a change of contact details if duly communicated to MyFastX through the support ID. Any change in such information may lead to increasing the delivery timelines which will be the sole liability and responsibility of the consignor alone. MyFastX reserves its right to refuse the booking of any consignment without assigning any reason whatsoever</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Sunday Pickup is not available</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Open Deliveries will not be entertained</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Shipments with a declared value exceeding INR 49,999 cannot be shipped via MyFastX</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">In case of non-acceptance of the RTO shipment by the shipper or in case the shipper is not reachable for RTO shipment, MyFastX reserves the right to levy suitable demurrage / incidental charges for extended storage of such products for any period exceeding 7(seven) days from initiation of the returns and up to 14 (fourteen) days from such date</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">In case of non-acceptance of the products beyond 14 (fourteen) days, MyFastX has the right to dispose of such products and the user will forfeit all claims in this regard towards MyFastX. Also, user will be required to pay charges for disposing of the product, along with all other charges (including demurrage / incidental charges)</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Volumetric weight Calculation: [Length(cms) X Breadth(cms) X Height(cms)]/5000</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Shipments with incorrect weight and dimensions would go on hold and would affect the actual delivery date. MyFastX shall not be liable for any losses incurred due to shipments kept on hold because of incorrect weight and dimensions.</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">In case of any dispute, MyFastX reserves the right to hold the goods until the differential amount is paid. In this regard, MyFastX shall have the right to lien on these disputed goods.</li>
                            <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">In case of volumetric weight or dead weight is higher than the declared weight post scanning at sort center, revised amount will be additionally charged by MyFastX as per the below mentioned rates (Table image attached),</li>
                            <table className="border-2 m-4">
                                <tr className=''>
                                    <td className="border-2 p-4 text-lg font-semibold">Per KG Rate</td>
                                    <td className="border-2 p-4 text-lg font-semibold">EXPRESS Rs. 120</td>
                                    <td className="border-2 p-4 text-lg font-semibold">STANDARD Rs. 60</td>
                                </tr>
                            </table>
                        </ul>
                </div>
                <div className="w-full pb-5 md:pb-8">
                    <h1 className="font-inter text-[15px] md:text-lg font-semibold text-[#000000cc]">RESTRICTED ITEMS/MATERIALS</h1>
                    <ul className="list-disc pl-6">
                        <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Items not acceptable for carriage:  The Parties hereby declare that the consignment covered under this consignment note does not include any articles restricted to be carried in courier mode, contrabands or such commodities which can cause safety hazards as specified by the current edition of IATA DG regulation</li>
                        <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Perishable Articles: Parties shall not tender for transportation any consignment containing perishable articles having shelf life of less than 7 days. MyFastX shall not be liable for any loss or damage to any such consignment arising consequent to any delay in delivery</li>
                        <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">The consignor shall not book any consignment containing any of the following nor can MyFastX knowingly carry any of the following items:</li>
                        <ul className='list-[circle] pl-8 md:pl-12'>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>Highly perishable food items,</li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>LEDs, LCDs, plasma, OLED and any kind of television screens,</li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>Liquid product, livestock, perishables, live plants,</li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>Flammable items (firecrackers, oil cans, adhesives, paint cans), explosives (arms, ammunition, fireworks, flares, gunpowder, airbag inflators), fire extinguishers, electric lighter/cigarette </li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>Platinum, gold, silver, artificial jewelry, gem, precious, semi-precious metals or stones in any form including bricks</li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>Alcohol/tobacco/ medicines/drugs/poisonous goods, toxic and infectious items,</li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>Valuable items, electronic devices, high-capacity batteries such as car batteries, generator batteries,</li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>Machinery parts containing oil, grease, fuel or batteries, corrosive items (acids, chemicals),</li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>Radioactive material, Magnetized materials, Pressurized Containers, Narcotic Substances & Medical and research equipment</li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>Indian postal articles such as stamps and articles like coins, banknotes, currency notes, Sodexo or securities of any kind payable to bearer, traveler's cheques,</li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>Gambling devices, lottery tickets, pornographic material,</li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>Dry ice used for packaging or temperature control and other items considered contraband under the Indian Postal law.</li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>Further, consignors will not hand over any secure original documents including but not restricted to passport, Aadhar Cards, bank statements, credit cards, debit cards, bank cheques and / or currency items, passports amongst other documents.</li>
                            <li className='font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium'>MyFastX is not licensed to carry the above-mentioned products/ documents and shall have no liability in such cases if such product is handed over without the consent of MyFastX for delivery by the consignor</li>
                        </ul>
                    </ul>
                </div>
                <div className="w-full pb-5 md:pb-8">
                    <h1 className="font-inter text-[15px] md:text-lg font-semibold text-[#000000cc]">DAMAGE/LOSS/REFUND</h1>
                    <ul className="list-disc pl-6">
                        <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">MyFastX shall not deliver consignments to PO Box addresses. Wherever MyFastX carries out drop-box deliveries such as to ministry offices, armed forces establishments, certain government offices & high security zones, etc. MyFastX shall not be providing proof of delivery(POD) and the parties shall accept the information provided as final. In case of any requirement of POD, customer shall request for the POD within 5 days after delivery. Post 5 days of delivery MyFastX will be under no obligation to provide POD</li>
                        <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Limited liability for Delay: In the event of any delay in delivery of a consignment, MyFastX shall not be liable for any consequential or indirect losses or damages, including but not limited to loss of income or profits or claims by the parties or any other entity affected because of a delay</li>
                        <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Freight Refund: The refund of freight shall not be entertained if a service failure is resulted from any Force Majeure conditions such as strikes, bandhs, elections, rains, floods, fire, accidents or other natural calamities and any other events such as sudden or planned road closures or traffic diversions during festivals, political rallies, religious processions etc. or any other reasons beyond direct control of MyFastX. This also includes any routine or sudden inspections carried out by any authorities or tax recovery agencies such as but not limited to Excise, Customs, Sales Tax, municipalities or any other authorities competent to inspect goods or vehicles</li>
                        <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">Any claims or disputes arising out of our services, shall be solely adjudicated before the courts at Delhi</li>
                        <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">In case of verified damage or loss of shipment due to mishandling by courier partner, MyFastX shall be covering maximum liability up to Rs.2000 based on material invoice. For the material value above Rs 2000 MyFastX will be providing a certificate of facts to customers. In case of unavailability of material invoice refund claims for damage and loss scenarios will be invalid.</li>
                        <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">For refund of damage cases customers need to share required proofs like photos and videos of the package before and after opening the package.</li>
                        <li className="font-inter text-[13px] md:text-[15px] text-[#2d2c2cd8] font-medium">For any damage cases the customer has to intimate MyFastX via call or email within 24 hours post-delivery of the package.</li>
                    </ul>
                </div>
            </div>
        </div>
    )
}

export default PackagingInstruction;
